name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: build
      run: make build

    - name: test
      run: make test

    - name: install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: vulncheck
      run: make vulncheck
